//
// Created by cobak on 11.02.2022.
//

#ifndef TASK_10_PERSONALBUDGETPROFESSIONALMOBILEVERSION__SUMMINGSEGMENTTREE_H
#define TASK_10_PERSONALBUDGETPROFESSIONALMOBILEVERSION__SUMMINGSEGMENTTREE_H



class SummingSegmentTree {

};


#endif //TASK_10_PERSONALBUDGETPROFESSIONALMOBILEVERSION__SUMMINGSEGMENTTREE_H
